"""
Graph search tools for Zotero MCP server.

Reads a pre-built knowledge graph (graph.json) generated by
szotero_llm_metadata's `--build-graph` command. No graph construction
or NetworkX dependency — all queries work against the JSON directly.

Three tools:
  - zotero_graph_search: keyword search across titles/tags/community labels
  - zotero_graph_explore_item: full graph context for a single Zotero item
  - zotero_graph_community_info: list communities or get community detail
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fastmcp import Context

from .server import mcp

_GRAPH_JSON = Path("/Users/tomas/Desktop/szotero_llm_metadata/graph/graph.json")
_graph_cache: dict | None = None


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _load_graph_data() -> dict[str, Any]:
    """Load graph.json with in-memory cache."""
    global _graph_cache
    if _graph_cache is None:
        with open(_GRAPH_JSON, encoding="utf-8") as f:
            _graph_cache = json.load(f)
    return _graph_cache


def _build_edge_index(data: dict) -> dict[str, list[dict]]:
    """Build node_id → list of edges for fast neighbor lookup."""
    idx: dict[str, list[dict]] = {}
    for edge in data.get("edges", []):
        src = edge.get("source", "")
        tgt = edge.get("target", "")
        if src:
            idx.setdefault(src, []).append(edge)
        if tgt:
            idx.setdefault(tgt, []).append(edge)
    return idx


def _build_nodes_map(data: dict) -> dict[str, dict]:
    """Build node_id → node dict for fast lookup."""
    return {n["id"]: n for n in data.get("nodes", []) if "id" in n}


def _format_neighbors(
    node_id: str,
    edge_index: dict[str, list[dict]],
    nodes_map: dict[str, dict],
    limit: int = 8,
) -> list[str]:
    """Format neighbor list, sorted by edge weight."""
    edges = edge_index.get(node_id, [])
    sorted_edges = sorted(edges, key=lambda e: e.get("weight", 1), reverse=True)
    lines = []
    for edge in sorted_edges[:limit]:
        neighbor_id = edge.get("target", "") if edge.get("source") == node_id else edge.get("source", "")
        neighbor = nodes_map.get(neighbor_id)
        neighbor_label = neighbor.get("label", neighbor_id) if neighbor else neighbor_id
        rel = edge.get("relation", "")
        tags = ", ".join(edge.get("shared_tags", [])[:3])
        weight = edge.get("weight", 1)
        lines.append(f"- `{neighbor_label}` ({rel}, weight={weight}, tags: {tags})")
    return lines


def _ensure_graph() -> str | None:
    """Return error message if graph.json not found, else None."""
    if not _GRAPH_JSON.exists():
        return "No graph found. Run `python __main__.py --build-graph` in szotero_llm_metadata first."
    return None


# ---------------------------------------------------------------------------
# Tool 1: zotero_graph_search
# ---------------------------------------------------------------------------

@mcp.tool(
    name="zotero_graph_search",
    description="Search your Zotero knowledge graph by keyword. Matches item titles, tags, and community labels. Returns matched items with their community context and top neighbors."
)
def graph_search(
    query: str,
    top_n: int = 10,
    *,
    ctx: Context
) -> str:
    """Keyword search across the knowledge graph.

    Matches item titles and tags. If query matches a community label,
    also returns that community's members. Each matched item includes
    its community name and top 3 neighbors by connection strength.

    Args:
        query: Search keyword (e.g. "渗透测试", "EDR", "大语言模型").
        top_n: Max items to return (default 10).
    """
    try:
        err = _ensure_graph()
        if err:
            return err

        data = _load_graph_data()
        nodes_map = _build_nodes_map(data)
        edge_index = _build_edge_index(data)

        query_lower = query.lower()
        output: list[str] = []

        # Check community label match
        matched_community = None
        for cid_str, comm in data.get("communities", {}).items():
            label = comm.get("label", "").lower()
            if query_lower in label or label in query_lower:
                matched_community = (cid_str, comm)
                break

        # Search items by title and tags
        matched_nodes = []
        for node in data.get("nodes", []):
            node_label = node.get("label", "").lower()
            node_tags = " ".join(node.get("tags_normalized", [])).lower()
            if query_lower in node_label or query_lower in node_tags:
                matched_nodes.append(node)

        # Deduplicate: community members shown separately
        if matched_community and matched_nodes:
            comm_members = set(matched_community[1].get("members", []))
            matched_nodes = [n for n in matched_nodes if n.get("id") not in comm_members]

        # Community detail
        if matched_community:
            cid_str, comm = matched_community
            label = comm.get("label", f"Community {cid_str}")
            size = comm.get("size", len(comm.get("members", [])))
            cohesion = comm.get("cohesion", 0)
            members = comm.get("members", [])

            output.append(f"# Community: {label}")
            output.append(f"**{size} items · cohesion: {cohesion}**")
            output.append("")
            output.append("## Members")
            for mid in members[:top_n]:
                m_node = nodes_map.get(mid)
                if m_node:
                    m_label = m_node.get("label", mid)
                    m_degree = len(edge_index.get(mid, []))
                    output.append(f"- `{m_label}` ({m_degree} connections)")
            if len(members) > top_n:
                output.append(f"... and {len(members) - top_n} more")
            output.append("")

        # Item matches
        if matched_nodes:
            if not matched_community:
                output.append(f"# Search: \"{query}\"")
            else:
                output.append("## Also matched (outside community)")
            output.append(f"Found {len(matched_nodes)} items")
            output.append("")
            for node in matched_nodes[:top_n]:
                nid = node.get("id", "")
                n_label = node.get("label", nid)
                n_comm = node.get("community_label", "Unknown")
                n_degree = len(edge_index.get(nid, []))
                output.append(f"- **{n_label}** — community: {n_comm}, {n_degree} connections")
                neighbors = _format_neighbors(nid, edge_index, nodes_map, limit=5)
                for nb in neighbors[:3]:
                    output.append(f"  {nb}")

        if not matched_community and not matched_nodes:
            output.append(f"No matches for \"{query}\" in the knowledge graph.")
            output.append("")
            output.append("Available communities:")
            for cid_str, comm in data.get("communities", {}).items():
                label = comm.get("label", f"Community {cid_str}")
                size = comm.get("size", 0)
                output.append(f"- {label} ({size} items)")

        return "\n".join(output)

    except Exception as e:
        ctx.error(f"Error searching graph: {str(e)}")
        return f"Error searching graph: {str(e)}"


# ---------------------------------------------------------------------------
# Tool 2: zotero_graph_explore_item
# ---------------------------------------------------------------------------

@mcp.tool(
    name="zotero_graph_explore_item",
    description="Explore the full graph context of a Zotero item — its community, tags, and all neighbors sorted by connection strength."
)
def graph_explore_item(
    item_key: str,
    neighbor_limit: int = 10,
    *,
    ctx: Context
) -> str:
    """Get the complete graph context for a single Zotero item.

    Returns: title, community, tags, total connections, and neighbors
    sorted by edge weight (strongest connections first).

    Args:
        item_key: Zotero item key (8-char alphanumeric, e.g. "ABCD1234").
        neighbor_limit: Max neighbors to list (default 10).
    """
    try:
        err = _ensure_graph()
        if err:
            return err

        data = _load_graph_data()
        nodes_map = _build_nodes_map(data)
        edge_index = _build_edge_index(data)

        node = nodes_map.get(item_key)
        if not node:
            return f"Item key '{item_key}' not found in graph."

        cid = node.get("community")
        comm_label = node.get("community_label", "Unknown")
        tags = ", ".join(node.get("tags_normalized", [])[:8])
        degree = len(edge_index.get(item_key, []))

        output: list[str] = []
        output.append(f"# {node.get('label', item_key)}")
        output.append(f"**Community:** {comm_label} (#{cid})")
        output.append(f"**Tags:** {tags}")
        output.append(f"**Connections:** {degree}")
        output.append("")

        neighbors = _format_neighbors(item_key, edge_index, nodes_map, limit=neighbor_limit)
        if neighbors:
            output.append("## Neighbors (by connection strength)")
            output.extend(neighbors)

        return "\n".join(output)

    except Exception as e:
        ctx.error(f"Error exploring item: {str(e)}")
        return f"Error exploring item: {str(e)}"


# ---------------------------------------------------------------------------
# Tool 3: zotero_graph_community_info
# ---------------------------------------------------------------------------

@mcp.tool(
    name="zotero_graph_community_info",
    description="Browse community structure in your Zotero knowledge graph. No argument returns all communities; provide a label to get community detail with member list."
)
def graph_community_info(
    community_label: str = "",
    top_n: int = 15,
    *,
    ctx: Context
) -> str:
    """List all communities or get details for a specific community.

    No argument → returns overview of all communities with sizes and cohesion.
    With community_label → returns members list, cohesion, and graph stats.

    Args:
        community_label: Community name to inspect (e.g. "红队技术", "大语言模型").
            Empty string returns all communities.
        top_n: Max members to list for a specific community (default 15).
    """
    try:
        err = _ensure_graph()
        if err:
            return err

        data = _load_graph_data()
        nodes_map = _build_nodes_map(data)
        edge_index = _build_edge_index(data)

        output: list[str] = []

        # No label → overview
        if not community_label:
            output.append("# Knowledge Graph Communities")
            for cid_str, comm in data.get("communities", {}).items():
                label = comm.get("label", f"Community {cid_str}")
                size = comm.get("size", len(comm.get("members", [])))
                cohesion = comm.get("cohesion", 0)
                output.append(f"- **{label}** ({size} items, cohesion: {cohesion})")
            stats = data.get("stats", {})
            validation = data.get("validation", {})
            output.append("")
            output.append(
                f"Total: {stats.get('nodes', 0)} items · {stats.get('edges', 0)} edges "
                f"· {stats.get('avg_degree', 0)} avg degree · Modularity: {validation.get('modularity', 0)}"
            )
            return "\n".join(output)

        # Find matching community
        label_lower = community_label.lower()
        matched = None
        for cid_str, comm in data.get("communities", {}).items():
            clabel = comm.get("label", "").lower()
            if label_lower in clabel or clabel in label_lower:
                matched = (cid_str, comm)
                break

        if not matched:
            output.append(f"Community \"{community_label}\" not found.")
            output.append("")
            output.append("Available communities:")
            for cid_str, comm in data.get("communities", {}).items():
                label = comm.get("label", f"Community {cid_str}")
                size = comm.get("size", 0)
                output.append(f"- {label} ({size} items)")
            return "\n".join(output)

        cid_str, comm = matched
        label = comm.get("label", f"Community {cid_str}")
        size = comm.get("size", len(comm.get("members", [])))
        cohesion = comm.get("cohesion", 0)
        members = comm.get("members", [])

        output.append(f"# Community: {label}")
        output.append(f"**{size} items · cohesion: {cohesion}**")
        output.append("")
        output.append("## Members")
        for mid in members[:top_n]:
            m_node = nodes_map.get(mid)
            if m_node:
                m_label = m_node.get("label", mid)
                m_degree = len(edge_index.get(mid, []))
                m_tags = ", ".join(m_node.get("tags_normalized", [])[:3])
                output.append(f"- `{m_label}` ({m_degree} connections, tags: {m_tags})")
        if len(members) > top_n:
            output.append(f"... and {len(members) - top_n} more")

        return "\n".join(output)

    except Exception as e:
        ctx.error(f"Error getting community info: {str(e)}")
        return f"Error getting community info: {str(e)}"